disabled_rules: # rule identifiers to exclude from running
  - vertical_parameter_alignment
  - identifier_name
  - trailing_whitespace
  - nesting
  - switch_case_alignment
opt_in_rules: # some rules are only opt-in
  - empty_count
  - single_test_class
  - switch_case_on_newline
  - syntactic_sugar
#included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Resources/Generated
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
line_length: 140
type_body_length:
  - 400 # warning
  - 500 # error
file_length:
  warning: 500
  error: 600
type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded: 
      iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - i
    - j
    - x
    - y
    - z
    - URL
    - GlobalAPIKey
reporter: "xcode"