language: swift
osx_image: xcode10
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE="iOS Example.xcworkspace"
  - FRAMEWORK_PROJECT="ChatViewController.xcodeproj"
  - FRAMEWORK_SCHEME="ChatViewController"
  - EXAMPLE_SCHEME="iOS Example"
  matrix:
    - DESTINATION="OS=11.4,name=iPhone X"          PROJECT="$FRAMEWORK_PROJECT"  BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"   PROJECT="$FRAMEWORK_PROJECT"  BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=12.0,name=iPhone X"          PROJECT="$FRAMEWORK_PROJECT"  BUILD_EXAMPLE="YES" POD_LINT="NO"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - cd Example && pod update
  - cd ..

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug
  - xcodebuild -project "$PROJECT" -scheme "$FRAMEWORK_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;

  # Build Framework in Release
  - xcodebuild -project "$PROJECT" -scheme "$FRAMEWORK_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;

  # Build Example in Debug if specified
  - cd Example
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - cd ..
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
