language: swift
osx_image: xcode10.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE="iOS Example.xcworkspace"
  - EXAMPLE_SCHEME="iOS Example"
  matrix:
    - DESTINATION="OS=11.4,name=iPhone X"          PROJECT="$FRAMEWORK_PROJECT"  BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=12.1,name=iPhone X"          PROJECT="$FRAMEWORK_PROJECT"  BUILD_EXAMPLE="YES" POD_LINT="NO"

before_install:
  - gem install cocoapods --prerelease --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod --version
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks
  - cd Example && pod update
  - cd ..

script:
  # Build Example in Debug if specified
  - cd Example
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - cd ..
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
